/*
 *  Milkyway Technology file generated by TechBuilder version 3.3.0
 *  Metal Stack Option = 1P8M_1TM
 *
 *     Copyright (c) 2012 ARM, Inc.
 *
 *     ALL RIGHTS RESERVED
 *
 *     The confidential and proprietary information contained in this file
 *     may only be used by a person authorised under and to the extent
 *     permitted by a subsisting licensing agreement from ARM Limited.
 *
 *     This entire notice must be reproduced on all copies of this file
 *     and copies of this file may only be made by a person if such person
 *     is permitted to do so under the terms of a subsisting license
 *     agreement from ARM Limited.
 */

Technology {
  name = "logic0040ll"
  unitTimeName = "ns"
  timePrecision = 1000
  unitLengthName = "micron"
  lengthPrecision = 1000
  unitVoltageName = "v"
  voltagePrecision = 1000000
  unitCurrentName = "ma"
  currentPrecision = 1000
  unitPowerName = "mw"
  powerPrecision = 100000
  unitResistanceName = "kohm"
  resistancePrecision = 10000000
  unitCapacitanceName = "pf"
  capacitancePrecision = 10000000
  unitInductanceName = "nh"
  inductancePrecision = 100
  gridResolution = 1
  minEdgeMode = 1
}

Layer "GT" {
  layerNumber = 30
  maskName = "poly"
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "dot"
  color = "cyan"
}

Layer "CT" {
  layerNumber = 50
  maskName = "polyCont"
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "rectangleX"
  color = "cyan"
  minSpacing = 0.08
}

Layer "M1" {
  layerNumber = 61
  maskName = "metal1"
  isDefaultLayer = 1
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "dot"
  color = "green"
  pitch = 0.14
  defaultWidth = 0.07
  minWidth = 0.07
  maxWidth = 4.5
  maxSegLenForRC = 2000
  minArea = 0.0196
  minEnclosedArea = 0.078
  minEdgeLength = 0.07
  maxNumMinEdge = 1
  fatTblDimension = 4
  fatTblThreshold = (  0.0, 0.225, 0.705, 1.505  )
  fatTblParallelLength = (  0.0, 0.305, 0.305, 1.505  )
  fatTblSpacing = (  0.07, 0.08, 0.175, 0.5, 
                     0.08, 0.08, 0.21, 0.5, 
                     0.175, 0.21, 0.21, 0.5, 
                     0.5, 0.5, 0.5, 0.5  )
  minSpacing = 0.07
}

Layer "V1" {
  layerNumber = 70
  maskName = "via1"
  isDefaultLayer = 1
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "rectangleX"
  color = "green"
  enclosedCutNumNeighbor = 4
  enclosedCutNeighborRange = 0.13
  enclosedCutToNeighborMinSpacing = 0.09
  fatTblDimension = 5
  fatTblThreshold = (  0.0, 0.145, 0.266, 0.526, 0.651  )
  fatTblFatContactNumber = (  1, 1, 1, 1, 1  )
  fatTblFatContactMinCuts = (  1, 1, 2, 3, 4  )
  minSpacing = 0.09
  sameNetMinSpacing = 0.07
}

Layer "M2" {
  layerNumber = 62
  maskName = "metal2"
  isDefaultLayer = 1
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "dot"
  color = "magenta"
  pitch = 0.14
  defaultWidth = 0.07
  minWidth = 0.07
  maxWidth = 4.5
  maxSegLenForRC = 2000
  minArea = 0.0196
  minEnclosedArea = 0.078
  minEdgeLength = 0.07
  maxNumMinEdge = 1
  fatTblDimension = 4
  fatTblThreshold = (  0.0, 0.225, 0.705, 1.505  )
  fatTblParallelLength = (  0.0, 0.305, 0.305, 1.505  )
  fatTblSpacing = (  0.07, 0.1, 0.175, 0.5, 
                     0.1, 0.1, 0.21, 0.5, 
                     0.175, 0.21, 0.21, 0.5, 
                     0.5, 0.5, 0.5, 0.5  )
  minSpacing = 0.07
}

Layer "V2" {
  layerNumber = 71
  maskName = "via2"
  isDefaultLayer = 1
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "rectangleX"
  color = "magenta"
  enclosedCutNumNeighbor = 4
  enclosedCutNeighborRange = 0.13
  enclosedCutToNeighborMinSpacing = 0.09
  fatTblDimension = 5
  fatTblThreshold = (  0.0, 0.14, 0.266, 0.526, 0.651  )
  fatTblFatContactNumber = (  26, 26, 26, 26, 26  )
  fatTblFatContactMinCuts = (  1, 1, 2, 3, 4  )
  minSpacing = 0.09
  sameNetMinSpacing = 0.07
}

Layer "M3" {
  layerNumber = 63
  maskName = "metal3"
  isDefaultLayer = 1
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "dot"
  color = "purple"
  pitch = 0.14
  defaultWidth = 0.07
  minWidth = 0.07
  maxWidth = 4.5
  maxSegLenForRC = 2000
  minArea = 0.0196
  minEnclosedArea = 0.078
  minEdgeLength = 0.07
  maxNumMinEdge = 1
  fatTblDimension = 4
  fatTblThreshold = (  0.0, 0.225, 0.705, 1.505  )
  fatTblParallelLength = (  0.0, 0.305, 0.305, 1.505  )
  fatTblSpacing = (  0.07, 0.1, 0.175, 0.5, 
                     0.1, 0.1, 0.21, 0.5, 
                     0.175, 0.21, 0.21, 0.5, 
                     0.5, 0.5, 0.5, 0.5  )
  minSpacing = 0.07
}

Layer "V3" {
  layerNumber = 72
  maskName = "via3"
  isDefaultLayer = 1
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "rectangleX"
  color = "purple"
  enclosedCutNumNeighbor = 4
  enclosedCutNeighborRange = 0.13
  enclosedCutToNeighborMinSpacing = 0.09
  fatTblDimension = 5
  fatTblThreshold = (  0.0, 0.14, 0.266, 0.526, 0.651  )
  fatTblFatContactNumber = (  51, 51, 51, 51, 51  )
  fatTblFatContactMinCuts = (  1, 1, 2, 3, 4  )
  minSpacing = 0.09
  sameNetMinSpacing = 0.07
}

Layer "M4" {
  layerNumber = 64
  maskName = "metal4"
  isDefaultLayer = 1
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "dot"
  color = "red"
  pitch = 0.14
  defaultWidth = 0.07
  minWidth = 0.07
  maxWidth = 4.5
  maxSegLenForRC = 2000
  minArea = 0.0196
  minEnclosedArea = 0.078
  minEdgeLength = 0.07
  maxNumMinEdge = 1
  fatTblDimension = 4
  fatTblThreshold = (  0.0, 0.225, 0.705, 1.505  )
  fatTblParallelLength = (  0.0, 0.305, 0.305, 1.505  )
  fatTblSpacing = (  0.07, 0.1, 0.175, 0.5, 
                     0.1, 0.1, 0.21, 0.5, 
                     0.175, 0.21, 0.21, 0.5, 
                     0.5, 0.5, 0.5, 0.5  )
  minSpacing = 0.07
}

Layer "V4" {
  layerNumber = 73
  maskName = "via4"
  isDefaultLayer = 1
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "rectangleX"
  color = "red"
  enclosedCutNumNeighbor = 4
  enclosedCutNeighborRange = 0.13
  enclosedCutToNeighborMinSpacing = 0.09
  fatTblDimension = 5
  fatTblThreshold = (  0.0, 0.14, 0.266, 0.526, 0.651  )
  fatTblFatContactNumber = (  76, 76, 76, 76, 76  )
  fatTblFatContactMinCuts = (  1, 1, 2, 3, 4  )
  minSpacing = 0.09
  sameNetMinSpacing = 0.07
}

Layer "M5" {
  layerNumber = 65
  maskName = "metal5"
  isDefaultLayer = 1
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "dot"
  color = "white"
  pitch = 0.14
  defaultWidth = 0.07
  minWidth = 0.07
  maxWidth = 4.5
  maxSegLenForRC = 2000
  minArea = 0.0196
  minEnclosedArea = 0.078
  minEdgeLength = 0.07
  maxNumMinEdge = 1
  fatTblDimension = 4
  fatTblThreshold = (  0.0, 0.225, 0.705, 1.505  )
  fatTblParallelLength = (  0.0, 0.305, 0.305, 1.505  )
  fatTblSpacing = (  0.07, 0.1, 0.175, 0.5, 
                     0.1, 0.1, 0.21, 0.5, 
                     0.175, 0.21, 0.21, 0.5, 
                     0.5, 0.5, 0.5, 0.5  )
  minSpacing = 0.07
}

Layer "V5" {
  layerNumber = 74
  maskName = "via5"
  isDefaultLayer = 1
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "rectangleX"
  color = "white"
  enclosedCutNumNeighbor = 4
  enclosedCutNeighborRange = 0.13
  enclosedCutToNeighborMinSpacing = 0.09
  fatTblDimension = 5
  fatTblThreshold = (  0.0, 0.14, 0.266, 0.526, 0.651  )
  fatTblFatContactNumber = (  101, 101, 101, 101, 101  )
  fatTblFatContactMinCuts = (  1, 1, 2, 3, 4  )
  minSpacing = 0.09
  sameNetMinSpacing = 0.07
}

Layer "M6" {
  layerNumber = 66
  maskName = "metal6"
  isDefaultLayer = 1
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "dot"
  color = "yellow"
  pitch = 0.14
  defaultWidth = 0.07
  minWidth = 0.07
  maxWidth = 4.5
  maxSegLenForRC = 2000
  minArea = 0.0196
  minEnclosedArea = 0.078
  minEdgeLength = 0.07
  maxNumMinEdge = 1
  fatTblDimension = 4
  fatTblThreshold = (  0.0, 0.225, 0.705, 1.505  )
  fatTblParallelLength = (  0.0, 0.305, 0.305, 1.505  )
  fatTblSpacing = (  0.07, 0.1, 0.175, 0.5, 
                     0.1, 0.1, 0.21, 0.5, 
                     0.175, 0.21, 0.21, 0.5, 
                     0.5, 0.5, 0.5, 0.5  )
  minSpacing = 0.07
}

Layer "V6" {
  layerNumber = 75
  maskName = "via6"
  isDefaultLayer = 1
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "rectangleX"
  color = "yellow"
  enclosedCutNumNeighbor = 4
  enclosedCutNeighborRange = 0.13
  enclosedCutToNeighborMinSpacing = 0.09
  fatTblDimension = 5
  fatTblThreshold = (  0.0, 0.14, 0.266, 0.526, 0.651  )
  fatTblFatContactNumber = (  126, 126, 126, 126, 126  )
  fatTblFatContactMinCuts = (  1, 1, 2, 3, 4  )
  minSpacing = 0.09
  sameNetMinSpacing = 0.07
}

Layer "M7" {
  layerNumber = 67
  maskName = "metal7"
  isDefaultLayer = 1
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "dot"
  color = "blue"
  pitch = 0.14
  defaultWidth = 0.07
  minWidth = 0.07
  maxWidth = 4.5
  maxSegLenForRC = 2000
  minArea = 0.0196
  minEnclosedArea = 0.078
  minEdgeLength = 0.07
  maxNumMinEdge = 1
  fatTblDimension = 4
  fatTblThreshold = (  0.0, 0.225, 0.705, 1.505  )
  fatTblParallelLength = (  0.0, 0.305, 0.305, 1.505  )
  fatTblSpacing = (  0.07, 0.1, 0.175, 0.5, 
                     0.1, 0.1, 0.21, 0.5, 
                     0.175, 0.21, 0.21, 0.5, 
                     0.5, 0.5, 0.5, 0.5  )
  minSpacing = 0.07
}

Layer "TV2" {
  layerNumber = 123
  maskName = "via7"
  isDefaultLayer = 1
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "rectangleX"
  color = "blue"
  enclosedCutNumNeighbor = 3
  enclosedCutNeighborRange = 0.56
  enclosedCutToNeighborMinSpacing = 0.5
  fatTblDimension = 4
  fatTblThreshold = (  0.0, 0.266, 0.526, 0.651  )
  fatTblThreshold2 = (  0.0, 0.266, 0.526, 0.651  )
  fat2DTblFatContactNumber = (  151, 151, 151, 151, 
                     151, 151, 151, 151, 
                     151, 151, 151, 151, 
                     151, 151, 151, 151  )
  fat2DTblFatContactMinCuts = (  1, 1, 1, 1, 
                     2, 2, 2, 2, 
                     3, 3, 3, 3, 
                     4, 4, 4, 4  )
  minSpacing = 0.36
}

Layer "TM2" {
  layerNumber = 122
  maskName = "metal8"
  isDefaultLayer = 1
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "dot"
  color = "cyan"
  pitch = 0.84
  defaultWidth = 0.4
  minWidth = 0.4
  maxWidth = 12.0
  maxSegLenForRC = 2000
  minArea = 0.42
  minEnclosedArea = 0.8
  minEdgeLength = 0.4
  maxNumMinEdge = 1
  fatTblDimension = 4
  fatTblThreshold = (  0.0, 1.505, 2.005, 4.005  )
  fatTblParallelLength = (  0.0, 4.005, 1.505, 1.505  )
  fatTblSpacing = (  0.4, 1.0, 0.6, 0.6, 
                     1.0, 1.0, 1.0, 1.0, 
                     0.6, 1.0, 0.6, 1.2, 
                     0.6, 1.0, 1.2, 1.2  )
  minSpacing = 0.4
}

Layer "PA" {
  layerNumber = 126
  maskName = "via8"
  isDefaultLayer = 1
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "rectangleX"
  color = "cyan"
  minSpacing = 2.0
}

Layer "ALPA" {
  layerNumber = 124
  maskName = "metal9"
  isDefaultLayer = 1
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "dot"
  color = "green"
  pitch = 8.0
  defaultWidth = 4.0
  minWidth = 4.0
  maxSegLenForRC = 2000
  minSpacing = 2.0
}

Layer "NW" {
  layerNumber = 14
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "magenta"
}

Layer "AA" {
  layerNumber = 10
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "purple"
}

Layer "V7" {
  layerNumber = 76
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "yellow"
}

Layer "M8" {
  layerNumber = 68
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "blue"
}

Layer "TV1" {
  layerNumber = 121
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "cyan"
}

Layer "TM1" {
  layerNumber = 120
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "green"
}

Layer "MnTXT_metal1" {
  layerNumber = 141
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "magenta"
}

Layer "MnTXT_metal2" {
  layerNumber = 142
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "purple"
}

Layer "MnTXT_metal3" {
  layerNumber = 143
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "red"
}

Layer "MnTXT_metal4" {
  layerNumber = 144
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "white"
}

Layer "MnTXT_metal5" {
  layerNumber = 145
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "yellow"
}

Layer "MnTXT_metal6" {
  layerNumber = 146
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "blue"
}

Layer "MnTXT_metal7" {
  layerNumber = 147
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "cyan"
}

Layer "MnTXT_metal8" {
  layerNumber = 148
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "green"
}

Layer "SN" {
  layerNumber = 40
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "red"
}

Layer "SP" {
  layerNumber = 43
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "white"
}

Layer "DSTR" {
  layerNumber = 138
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "yellow"
}

Layer "INST" {
  layerNumber = 60
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "green"
}

Layer "SDOP" {
  layerNumber = 99
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "purple"
}

Layer "CL" {
  layerNumber = 18
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "red"
}

Layer "RESP1" {
  layerNumber = 96
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "white"
}

Layer "MD" {
  layerNumber = 130
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "yellow"
}

Layer "ESD1" {
  layerNumber = 41
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "cyan"
}

Layer "BORDER" {
  layerNumber = 127
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "green"
}

Layer "TAPMARKER" {
  layerNumber = 1
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "magenta"
}

Layer "DUMBA" {
  layerNumber = 91
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "purple"
}

Layer "DUMBP" {
  layerNumber = 92
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "red"
}

Layer "VARMOS" {
  layerNumber = 93
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "white"
}

Layer "PW" {
  layerNumber = 20
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "magenta"
}

Layer "TTXT" {
  layerNumber = 87
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "purple"
}

Layer "CTXT" {
  layerNumber = 89
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "red"
}

Layer "SUBTXT" {
  layerNumber = 161
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "white"
}

Layer "WELTXT" {
  layerNumber = 162
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "yellow"
}

Layer "VTNH" {
  layerNumber = 46
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "blue"
}

Layer "VTPH" {
  layerNumber = 47
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "cyan"
}

Layer "LVN" {
  layerNumber = 2
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "green"
}

Layer "LVP" {
  layerNumber = 3
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "magenta"
}

Layer "DNW" {
  layerNumber = 19
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "white"
}

Layer "RDL" {
  layerNumber = 166
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "yellow"
}

Layer "BCB1" {
  layerNumber = 165
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "blue"
}

Layer "OPCBA" {
  layerNumber = 100
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "magenta"
}

Layer "OPCBP" {
  layerNumber = 101
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "purple"
}

Layer "OPCBM" {
  layerNumber = 102
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "red"
}

Layer "NC" {
  layerNumber = 21
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "yellow"
}

Layer "POLYTXT" {
  layerNumber = 164
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "blue"
}

Layer "TG" {
  layerNumber = 125
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "cyan"
}

Layer "SAB" {
  layerNumber = 48
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "green"
}

Layer "DIOMY" {
  layerNumber = 4
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "magenta"
}

Layer "RES_MARKER" {
  layerNumber = 171
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "yellow"
}

Layer "SUBD_BASE0" {
  layerNumber = 131
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "cyan"
}

Layer "M1DUB_BASE0" {
  layerNumber = 151
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "green"
}

Layer "M2DUB_BASE0" {
  layerNumber = 152
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "magenta"
}

Layer "M3DUB_BASE0" {
  layerNumber = 153
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "purple"
}

Layer "M4DUB_BASE0" {
  layerNumber = 154
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "red"
}

Layer "M5DUB_BASE0" {
  layerNumber = 155
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "white"
}

Layer "M6DUB_BASE0" {
  layerNumber = 156
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "yellow"
}

Layer "M7DUB_BASE0" {
  layerNumber = 157
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "blue"
}

Layer "M8DUB_BASE0" {
  layerNumber = 158
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "cyan"
}

Layer "ESDHV_BASE0" {
  layerNumber = 133
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "green"
}

LayerDataType "AADUM" {
  dataTypeNumber = 1
  layerNumber = 10
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "red"
}

LayerDataType "GTDUM" {
  dataTypeNumber = 1
  layerNumber = 30
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "white"
}

LayerDataType "MnTXT_topmetal1" {
  dataTypeNumber = 3
  layerNumber = 120
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "magenta"
}

LayerDataType "MnTXT_topmetal2" {
  dataTypeNumber = 3
  layerNumber = 122
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "purple"
}

LayerDataType "D2SRAM" {
  dataTypeNumber = 11
  layerNumber = 60
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "blue"
}

LayerDataType "DNSRAM" {
  dataTypeNumber = 2
  layerNumber = 60
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "cyan"
}

LayerDataType "VSIA" {
  dataTypeNumber = 63
  layerNumber = 63
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "magenta"
}

LayerDataType "SUBD" {
  dataTypeNumber = 1
  layerNumber = 131
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "blue"
}

LayerDataType "M1DUB" {
  dataTypeNumber = 1
  layerNumber = 151
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "white"
}

LayerDataType "M2DUB" {
  dataTypeNumber = 1
  layerNumber = 152
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "yellow"
}

LayerDataType "M3DUB" {
  dataTypeNumber = 1
  layerNumber = 153
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "blue"
}

LayerDataType "M4DUB" {
  dataTypeNumber = 1
  layerNumber = 154
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "cyan"
}

LayerDataType "M5DUB" {
  dataTypeNumber = 1
  layerNumber = 155
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "green"
}

LayerDataType "M6DUB" {
  dataTypeNumber = 1
  layerNumber = 156
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "magenta"
}

LayerDataType "M7DUB" {
  dataTypeNumber = 1
  layerNumber = 157
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "purple"
}

LayerDataType "M8DUB" {
  dataTypeNumber = 1
  layerNumber = 158
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "red"
}

LayerDataType "NCAP" {
  dataTypeNumber = 1
  layerNumber = 93
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "yellow"
}

LayerDataType "PCAP" {
  dataTypeNumber = 2
  layerNumber = 93
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "blue"
}

LayerDataType "ESDHV" {
  dataTypeNumber = 1
  layerNumber = 133
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "cyan"
}

LayerDataType "ESDIO2" {
  dataTypeNumber = 3
  layerNumber = 133
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "green"
}

LayerDataType "LVT" {
  dataTypeNumber = 12
  layerNumber = 159
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "purple"
}

LayerDataType "HVT" {
  dataTypeNumber = 11
  layerNumber = 159
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "red"
}

LayerDataType "STRAM" {
  dataTypeNumber = 1
  layerNumber = 60
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "cyan"
}

LayerDataType "DNSRAM" {
  dataTypeNumber = 2
  layerNumber = 60
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "green"
}

LayerDataType "PRBOUN" {
  dataTypeNumber = 1
  layerNumber = 127
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "white"
}

LayerDataType "GTDUM" {
  dataTypeNumber = 1
  layerNumber = 30
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "purple"
}

LayerDataType "RPDMY" {
  dataTypeNumber = 1
  layerNumber = 96
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "red"
}

LayerDataType "ALPA_TXT" {
  dataTypeNumber = 2
  layerNumber = 124
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "white"
}

LayerDataType "OVERDRIVE" {
  dataTypeNumber = 3
  layerNumber = 125
  visible = 1
  selectable = 1
  blink = 0
  lineStyle = "solid"
  pattern = "blank"
  color = "blue"
}

ContactCode "V1_0_XX_F0" {
  contactCodeNumber = 1
  cutLayer = "V1"
  lowerLayer = "M1"
  upperLayer = "M2"
  upperLayerEncWidth = 0.015
  upperLayerEncHeight = 0.015
  lowerLayerEncWidth = 0.015
  lowerLayerEncHeight = 0.015
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V1_1_XH_F0" {
  contactCodeNumber = 2
  cutLayer = "V1"
  lowerLayer = "M1"
  upperLayer = "M2"
  upperLayerEncWidth = 0.02
  upperLayerEncHeight = 0.01
  lowerLayerEncWidth = 0.015
  lowerLayerEncHeight = 0.015
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V1_1_XV_F0" {
  contactCodeNumber = 3
  cutLayer = "V1"
  lowerLayer = "M1"
  upperLayer = "M2"
  upperLayerEncWidth = 0.01
  upperLayerEncHeight = 0.02
  lowerLayerEncWidth = 0.015
  lowerLayerEncHeight = 0.015
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V1_2_XH_F0" {
  contactCodeNumber = 4
  cutLayer = "V1"
  lowerLayer = "M1"
  upperLayer = "M2"
  upperLayerEncWidth = 0.03
  upperLayerEncHeight = 0.0
  lowerLayerEncWidth = 0.015
  lowerLayerEncHeight = 0.015
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V1_2_XV_F0" {
  contactCodeNumber = 5
  cutLayer = "V1"
  lowerLayer = "M1"
  upperLayer = "M2"
  upperLayerEncWidth = 0.0
  upperLayerEncHeight = 0.03
  lowerLayerEncWidth = 0.015
  lowerLayerEncHeight = 0.015
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V1_3_VX_F0" {
  contactCodeNumber = 6
  cutLayer = "V1"
  lowerLayer = "M1"
  upperLayer = "M2"
  upperLayerEncWidth = 0.015
  upperLayerEncHeight = 0.015
  lowerLayerEncWidth = 0.01
  lowerLayerEncHeight = 0.02
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V1_3_HX_F0" {
  contactCodeNumber = 7
  cutLayer = "V1"
  lowerLayer = "M1"
  upperLayer = "M2"
  upperLayerEncWidth = 0.015
  upperLayerEncHeight = 0.015
  lowerLayerEncWidth = 0.02
  lowerLayerEncHeight = 0.01
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V1_4_VH_F0" {
  contactCodeNumber = 8
  cutLayer = "V1"
  lowerLayer = "M1"
  upperLayer = "M2"
  upperLayerEncWidth = 0.02
  upperLayerEncHeight = 0.01
  lowerLayerEncWidth = 0.01
  lowerLayerEncHeight = 0.02
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V1_4_HH_F0" {
  contactCodeNumber = 9
  cutLayer = "V1"
  lowerLayer = "M1"
  upperLayer = "M2"
  upperLayerEncWidth = 0.02
  upperLayerEncHeight = 0.01
  lowerLayerEncWidth = 0.02
  lowerLayerEncHeight = 0.01
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V1_4_VV_F0" {
  contactCodeNumber = 10
  cutLayer = "V1"
  lowerLayer = "M1"
  upperLayer = "M2"
  upperLayerEncWidth = 0.01
  upperLayerEncHeight = 0.02
  lowerLayerEncWidth = 0.01
  lowerLayerEncHeight = 0.02
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V1_4_HV_F0" {
  contactCodeNumber = 11
  cutLayer = "V1"
  lowerLayer = "M1"
  upperLayer = "M2"
  upperLayerEncWidth = 0.01
  upperLayerEncHeight = 0.02
  lowerLayerEncWidth = 0.02
  lowerLayerEncHeight = 0.01
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V1_5_VH_F0" {
  contactCodeNumber = 12
  cutLayer = "V1"
  lowerLayer = "M1"
  upperLayer = "M2"
  upperLayerEncWidth = 0.03
  upperLayerEncHeight = 0.0
  lowerLayerEncWidth = 0.01
  lowerLayerEncHeight = 0.02
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V1_5_HH_F0" {
  contactCodeNumber = 13
  cutLayer = "V1"
  lowerLayer = "M1"
  upperLayer = "M2"
  upperLayerEncWidth = 0.03
  upperLayerEncHeight = 0.0
  lowerLayerEncWidth = 0.02
  lowerLayerEncHeight = 0.01
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V1_5_VV_F0" {
  contactCodeNumber = 14
  cutLayer = "V1"
  lowerLayer = "M1"
  upperLayer = "M2"
  upperLayerEncWidth = 0.0
  upperLayerEncHeight = 0.03
  lowerLayerEncWidth = 0.01
  lowerLayerEncHeight = 0.02
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V1_5_HV_F0" {
  contactCodeNumber = 15
  cutLayer = "V1"
  lowerLayer = "M1"
  upperLayer = "M2"
  upperLayerEncWidth = 0.0
  upperLayerEncHeight = 0.03
  lowerLayerEncWidth = 0.02
  lowerLayerEncHeight = 0.01
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V1_6_VX_F0" {
  contactCodeNumber = 16
  cutLayer = "V1"
  lowerLayer = "M1"
  upperLayer = "M2"
  upperLayerEncWidth = 0.015
  upperLayerEncHeight = 0.015
  lowerLayerEncWidth = 0.0
  lowerLayerEncHeight = 0.03
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V1_6_HX_F0" {
  contactCodeNumber = 17
  cutLayer = "V1"
  lowerLayer = "M1"
  upperLayer = "M2"
  upperLayerEncWidth = 0.015
  upperLayerEncHeight = 0.015
  lowerLayerEncWidth = 0.03
  lowerLayerEncHeight = 0.0
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V1_7_VH_F0" {
  contactCodeNumber = 18
  cutLayer = "V1"
  lowerLayer = "M1"
  upperLayer = "M2"
  upperLayerEncWidth = 0.02
  upperLayerEncHeight = 0.01
  lowerLayerEncWidth = 0.0
  lowerLayerEncHeight = 0.03
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V1_7_HH_F0" {
  contactCodeNumber = 19
  cutLayer = "V1"
  lowerLayer = "M1"
  upperLayer = "M2"
  upperLayerEncWidth = 0.02
  upperLayerEncHeight = 0.01
  lowerLayerEncWidth = 0.03
  lowerLayerEncHeight = 0.0
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V1_7_VV_F0" {
  contactCodeNumber = 20
  cutLayer = "V1"
  lowerLayer = "M1"
  upperLayer = "M2"
  upperLayerEncWidth = 0.01
  upperLayerEncHeight = 0.02
  lowerLayerEncWidth = 0.0
  lowerLayerEncHeight = 0.03
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V1_7_HV_F0" {
  contactCodeNumber = 21
  cutLayer = "V1"
  lowerLayer = "M1"
  upperLayer = "M2"
  upperLayerEncWidth = 0.01
  upperLayerEncHeight = 0.02
  lowerLayerEncWidth = 0.03
  lowerLayerEncHeight = 0.0
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V1_8_VH_F0" {
  contactCodeNumber = 22
  cutLayer = "V1"
  lowerLayer = "M1"
  upperLayer = "M2"
  upperLayerEncWidth = 0.03
  upperLayerEncHeight = 0.0
  lowerLayerEncWidth = 0.0
  lowerLayerEncHeight = 0.03
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V1_8_HH_F0" {
  contactCodeNumber = 23
  cutLayer = "V1"
  lowerLayer = "M1"
  upperLayer = "M2"
  upperLayerEncWidth = 0.03
  upperLayerEncHeight = 0.0
  lowerLayerEncWidth = 0.03
  lowerLayerEncHeight = 0.0
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V1_8_VV_F0" {
  contactCodeNumber = 24
  cutLayer = "V1"
  lowerLayer = "M1"
  upperLayer = "M2"
  upperLayerEncWidth = 0.0
  upperLayerEncHeight = 0.03
  lowerLayerEncWidth = 0.0
  lowerLayerEncHeight = 0.03
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V1_8_HV_F0" {
  contactCodeNumber = 25
  cutLayer = "V1"
  lowerLayer = "M1"
  upperLayer = "M2"
  upperLayerEncWidth = 0.0
  upperLayerEncHeight = 0.03
  lowerLayerEncWidth = 0.03
  lowerLayerEncHeight = 0.0
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V2_0_XX_F0" {
  contactCodeNumber = 26
  cutLayer = "V2"
  lowerLayer = "M2"
  upperLayer = "M3"
  upperLayerEncWidth = 0.015
  upperLayerEncHeight = 0.015
  lowerLayerEncWidth = 0.015
  lowerLayerEncHeight = 0.015
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V2_1_XV_F0" {
  contactCodeNumber = 27
  cutLayer = "V2"
  lowerLayer = "M2"
  upperLayer = "M3"
  upperLayerEncWidth = 0.01
  upperLayerEncHeight = 0.02
  lowerLayerEncWidth = 0.015
  lowerLayerEncHeight = 0.015
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V2_1_XH_F0" {
  contactCodeNumber = 28
  cutLayer = "V2"
  lowerLayer = "M2"
  upperLayer = "M3"
  upperLayerEncWidth = 0.02
  upperLayerEncHeight = 0.01
  lowerLayerEncWidth = 0.015
  lowerLayerEncHeight = 0.015
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V2_2_XV_F0" {
  contactCodeNumber = 29
  cutLayer = "V2"
  lowerLayer = "M2"
  upperLayer = "M3"
  upperLayerEncWidth = 0.0
  upperLayerEncHeight = 0.03
  lowerLayerEncWidth = 0.015
  lowerLayerEncHeight = 0.015
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V2_2_XH_F0" {
  contactCodeNumber = 30
  cutLayer = "V2"
  lowerLayer = "M2"
  upperLayer = "M3"
  upperLayerEncWidth = 0.03
  upperLayerEncHeight = 0.0
  lowerLayerEncWidth = 0.015
  lowerLayerEncHeight = 0.015
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V2_3_HX_F0" {
  contactCodeNumber = 31
  cutLayer = "V2"
  lowerLayer = "M2"
  upperLayer = "M3"
  upperLayerEncWidth = 0.015
  upperLayerEncHeight = 0.015
  lowerLayerEncWidth = 0.02
  lowerLayerEncHeight = 0.01
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V2_3_VX_F0" {
  contactCodeNumber = 32
  cutLayer = "V2"
  lowerLayer = "M2"
  upperLayer = "M3"
  upperLayerEncWidth = 0.015
  upperLayerEncHeight = 0.015
  lowerLayerEncWidth = 0.01
  lowerLayerEncHeight = 0.02
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V2_4_HV_F0" {
  contactCodeNumber = 33
  cutLayer = "V2"
  lowerLayer = "M2"
  upperLayer = "M3"
  upperLayerEncWidth = 0.01
  upperLayerEncHeight = 0.02
  lowerLayerEncWidth = 0.02
  lowerLayerEncHeight = 0.01
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V2_4_VV_F0" {
  contactCodeNumber = 34
  cutLayer = "V2"
  lowerLayer = "M2"
  upperLayer = "M3"
  upperLayerEncWidth = 0.01
  upperLayerEncHeight = 0.02
  lowerLayerEncWidth = 0.01
  lowerLayerEncHeight = 0.02
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V2_4_HH_F0" {
  contactCodeNumber = 35
  cutLayer = "V2"
  lowerLayer = "M2"
  upperLayer = "M3"
  upperLayerEncWidth = 0.02
  upperLayerEncHeight = 0.01
  lowerLayerEncWidth = 0.02
  lowerLayerEncHeight = 0.01
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V2_4_VH_F0" {
  contactCodeNumber = 36
  cutLayer = "V2"
  lowerLayer = "M2"
  upperLayer = "M3"
  upperLayerEncWidth = 0.02
  upperLayerEncHeight = 0.01
  lowerLayerEncWidth = 0.01
  lowerLayerEncHeight = 0.02
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V2_5_HV_F0" {
  contactCodeNumber = 37
  cutLayer = "V2"
  lowerLayer = "M2"
  upperLayer = "M3"
  upperLayerEncWidth = 0.0
  upperLayerEncHeight = 0.03
  lowerLayerEncWidth = 0.02
  lowerLayerEncHeight = 0.01
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V2_5_VV_F0" {
  contactCodeNumber = 38
  cutLayer = "V2"
  lowerLayer = "M2"
  upperLayer = "M3"
  upperLayerEncWidth = 0.0
  upperLayerEncHeight = 0.03
  lowerLayerEncWidth = 0.01
  lowerLayerEncHeight = 0.02
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V2_5_HH_F0" {
  contactCodeNumber = 39
  cutLayer = "V2"
  lowerLayer = "M2"
  upperLayer = "M3"
  upperLayerEncWidth = 0.03
  upperLayerEncHeight = 0.0
  lowerLayerEncWidth = 0.02
  lowerLayerEncHeight = 0.01
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V2_5_VH_F0" {
  contactCodeNumber = 40
  cutLayer = "V2"
  lowerLayer = "M2"
  upperLayer = "M3"
  upperLayerEncWidth = 0.03
  upperLayerEncHeight = 0.0
  lowerLayerEncWidth = 0.01
  lowerLayerEncHeight = 0.02
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V2_6_HX_F0" {
  contactCodeNumber = 41
  cutLayer = "V2"
  lowerLayer = "M2"
  upperLayer = "M3"
  upperLayerEncWidth = 0.015
  upperLayerEncHeight = 0.015
  lowerLayerEncWidth = 0.03
  lowerLayerEncHeight = 0.0
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V2_6_VX_F0" {
  contactCodeNumber = 42
  cutLayer = "V2"
  lowerLayer = "M2"
  upperLayer = "M3"
  upperLayerEncWidth = 0.015
  upperLayerEncHeight = 0.015
  lowerLayerEncWidth = 0.0
  lowerLayerEncHeight = 0.03
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V2_7_HV_F0" {
  contactCodeNumber = 43
  cutLayer = "V2"
  lowerLayer = "M2"
  upperLayer = "M3"
  upperLayerEncWidth = 0.01
  upperLayerEncHeight = 0.02
  lowerLayerEncWidth = 0.03
  lowerLayerEncHeight = 0.0
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V2_7_VV_F0" {
  contactCodeNumber = 44
  cutLayer = "V2"
  lowerLayer = "M2"
  upperLayer = "M3"
  upperLayerEncWidth = 0.01
  upperLayerEncHeight = 0.02
  lowerLayerEncWidth = 0.0
  lowerLayerEncHeight = 0.03
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V2_7_HH_F0" {
  contactCodeNumber = 45
  cutLayer = "V2"
  lowerLayer = "M2"
  upperLayer = "M3"
  upperLayerEncWidth = 0.02
  upperLayerEncHeight = 0.01
  lowerLayerEncWidth = 0.03
  lowerLayerEncHeight = 0.0
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V2_7_VH_F0" {
  contactCodeNumber = 46
  cutLayer = "V2"
  lowerLayer = "M2"
  upperLayer = "M3"
  upperLayerEncWidth = 0.02
  upperLayerEncHeight = 0.01
  lowerLayerEncWidth = 0.0
  lowerLayerEncHeight = 0.03
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V2_8_HV_F0" {
  contactCodeNumber = 47
  cutLayer = "V2"
  lowerLayer = "M2"
  upperLayer = "M3"
  upperLayerEncWidth = 0.0
  upperLayerEncHeight = 0.03
  lowerLayerEncWidth = 0.03
  lowerLayerEncHeight = 0.0
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V2_8_VV_F0" {
  contactCodeNumber = 48
  cutLayer = "V2"
  lowerLayer = "M2"
  upperLayer = "M3"
  upperLayerEncWidth = 0.0
  upperLayerEncHeight = 0.03
  lowerLayerEncWidth = 0.0
  lowerLayerEncHeight = 0.03
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V2_8_HH_F0" {
  contactCodeNumber = 49
  cutLayer = "V2"
  lowerLayer = "M2"
  upperLayer = "M3"
  upperLayerEncWidth = 0.03
  upperLayerEncHeight = 0.0
  lowerLayerEncWidth = 0.03
  lowerLayerEncHeight = 0.0
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V2_8_VH_F0" {
  contactCodeNumber = 50
  cutLayer = "V2"
  lowerLayer = "M2"
  upperLayer = "M3"
  upperLayerEncWidth = 0.03
  upperLayerEncHeight = 0.0
  lowerLayerEncWidth = 0.0
  lowerLayerEncHeight = 0.03
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V3_0_XX_F0" {
  contactCodeNumber = 51
  cutLayer = "V3"
  lowerLayer = "M3"
  upperLayer = "M4"
  upperLayerEncWidth = 0.015
  upperLayerEncHeight = 0.015
  lowerLayerEncWidth = 0.015
  lowerLayerEncHeight = 0.015
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V3_1_XH_F0" {
  contactCodeNumber = 52
  cutLayer = "V3"
  lowerLayer = "M3"
  upperLayer = "M4"
  upperLayerEncWidth = 0.02
  upperLayerEncHeight = 0.01
  lowerLayerEncWidth = 0.015
  lowerLayerEncHeight = 0.015
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V3_1_XV_F0" {
  contactCodeNumber = 53
  cutLayer = "V3"
  lowerLayer = "M3"
  upperLayer = "M4"
  upperLayerEncWidth = 0.01
  upperLayerEncHeight = 0.02
  lowerLayerEncWidth = 0.015
  lowerLayerEncHeight = 0.015
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V3_2_XH_F0" {
  contactCodeNumber = 54
  cutLayer = "V3"
  lowerLayer = "M3"
  upperLayer = "M4"
  upperLayerEncWidth = 0.03
  upperLayerEncHeight = 0.0
  lowerLayerEncWidth = 0.015
  lowerLayerEncHeight = 0.015
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V3_2_XV_F0" {
  contactCodeNumber = 55
  cutLayer = "V3"
  lowerLayer = "M3"
  upperLayer = "M4"
  upperLayerEncWidth = 0.0
  upperLayerEncHeight = 0.03
  lowerLayerEncWidth = 0.015
  lowerLayerEncHeight = 0.015
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V3_3_VX_F0" {
  contactCodeNumber = 56
  cutLayer = "V3"
  lowerLayer = "M3"
  upperLayer = "M4"
  upperLayerEncWidth = 0.015
  upperLayerEncHeight = 0.015
  lowerLayerEncWidth = 0.01
  lowerLayerEncHeight = 0.02
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V3_3_HX_F0" {
  contactCodeNumber = 57
  cutLayer = "V3"
  lowerLayer = "M3"
  upperLayer = "M4"
  upperLayerEncWidth = 0.015
  upperLayerEncHeight = 0.015
  lowerLayerEncWidth = 0.02
  lowerLayerEncHeight = 0.01
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V3_4_VH_F0" {
  contactCodeNumber = 58
  cutLayer = "V3"
  lowerLayer = "M3"
  upperLayer = "M4"
  upperLayerEncWidth = 0.02
  upperLayerEncHeight = 0.01
  lowerLayerEncWidth = 0.01
  lowerLayerEncHeight = 0.02
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V3_4_HH_F0" {
  contactCodeNumber = 59
  cutLayer = "V3"
  lowerLayer = "M3"
  upperLayer = "M4"
  upperLayerEncWidth = 0.02
  upperLayerEncHeight = 0.01
  lowerLayerEncWidth = 0.02
  lowerLayerEncHeight = 0.01
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V3_4_VV_F0" {
  contactCodeNumber = 60
  cutLayer = "V3"
  lowerLayer = "M3"
  upperLayer = "M4"
  upperLayerEncWidth = 0.01
  upperLayerEncHeight = 0.02
  lowerLayerEncWidth = 0.01
  lowerLayerEncHeight = 0.02
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V3_4_HV_F0" {
  contactCodeNumber = 61
  cutLayer = "V3"
  lowerLayer = "M3"
  upperLayer = "M4"
  upperLayerEncWidth = 0.01
  upperLayerEncHeight = 0.02
  lowerLayerEncWidth = 0.02
  lowerLayerEncHeight = 0.01
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V3_5_VH_F0" {
  contactCodeNumber = 62
  cutLayer = "V3"
  lowerLayer = "M3"
  upperLayer = "M4"
  upperLayerEncWidth = 0.03
  upperLayerEncHeight = 0.0
  lowerLayerEncWidth = 0.01
  lowerLayerEncHeight = 0.02
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V3_5_HH_F0" {
  contactCodeNumber = 63
  cutLayer = "V3"
  lowerLayer = "M3"
  upperLayer = "M4"
  upperLayerEncWidth = 0.03
  upperLayerEncHeight = 0.0
  lowerLayerEncWidth = 0.02
  lowerLayerEncHeight = 0.01
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V3_5_VV_F0" {
  contactCodeNumber = 64
  cutLayer = "V3"
  lowerLayer = "M3"
  upperLayer = "M4"
  upperLayerEncWidth = 0.0
  upperLayerEncHeight = 0.03
  lowerLayerEncWidth = 0.01
  lowerLayerEncHeight = 0.02
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V3_5_HV_F0" {
  contactCodeNumber = 65
  cutLayer = "V3"
  lowerLayer = "M3"
  upperLayer = "M4"
  upperLayerEncWidth = 0.0
  upperLayerEncHeight = 0.03
  lowerLayerEncWidth = 0.02
  lowerLayerEncHeight = 0.01
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V3_6_VX_F0" {
  contactCodeNumber = 66
  cutLayer = "V3"
  lowerLayer = "M3"
  upperLayer = "M4"
  upperLayerEncWidth = 0.015
  upperLayerEncHeight = 0.015
  lowerLayerEncWidth = 0.0
  lowerLayerEncHeight = 0.03
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V3_6_HX_F0" {
  contactCodeNumber = 67
  cutLayer = "V3"
  lowerLayer = "M3"
  upperLayer = "M4"
  upperLayerEncWidth = 0.015
  upperLayerEncHeight = 0.015
  lowerLayerEncWidth = 0.03
  lowerLayerEncHeight = 0.0
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V3_7_VH_F0" {
  contactCodeNumber = 68
  cutLayer = "V3"
  lowerLayer = "M3"
  upperLayer = "M4"
  upperLayerEncWidth = 0.02
  upperLayerEncHeight = 0.01
  lowerLayerEncWidth = 0.0
  lowerLayerEncHeight = 0.03
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V3_7_HH_F0" {
  contactCodeNumber = 69
  cutLayer = "V3"
  lowerLayer = "M3"
  upperLayer = "M4"
  upperLayerEncWidth = 0.02
  upperLayerEncHeight = 0.01
  lowerLayerEncWidth = 0.03
  lowerLayerEncHeight = 0.0
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V3_7_VV_F0" {
  contactCodeNumber = 70
  cutLayer = "V3"
  lowerLayer = "M3"
  upperLayer = "M4"
  upperLayerEncWidth = 0.01
  upperLayerEncHeight = 0.02
  lowerLayerEncWidth = 0.0
  lowerLayerEncHeight = 0.03
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V3_7_HV_F0" {
  contactCodeNumber = 71
  cutLayer = "V3"
  lowerLayer = "M3"
  upperLayer = "M4"
  upperLayerEncWidth = 0.01
  upperLayerEncHeight = 0.02
  lowerLayerEncWidth = 0.03
  lowerLayerEncHeight = 0.0
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V3_8_VH_F0" {
  contactCodeNumber = 72
  cutLayer = "V3"
  lowerLayer = "M3"
  upperLayer = "M4"
  upperLayerEncWidth = 0.03
  upperLayerEncHeight = 0.0
  lowerLayerEncWidth = 0.0
  lowerLayerEncHeight = 0.03
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V3_8_HH_F0" {
  contactCodeNumber = 73
  cutLayer = "V3"
  lowerLayer = "M3"
  upperLayer = "M4"
  upperLayerEncWidth = 0.03
  upperLayerEncHeight = 0.0
  lowerLayerEncWidth = 0.03
  lowerLayerEncHeight = 0.0
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V3_8_VV_F0" {
  contactCodeNumber = 74
  cutLayer = "V3"
  lowerLayer = "M3"
  upperLayer = "M4"
  upperLayerEncWidth = 0.0
  upperLayerEncHeight = 0.03
  lowerLayerEncWidth = 0.0
  lowerLayerEncHeight = 0.03
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V3_8_HV_F0" {
  contactCodeNumber = 75
  cutLayer = "V3"
  lowerLayer = "M3"
  upperLayer = "M4"
  upperLayerEncWidth = 0.0
  upperLayerEncHeight = 0.03
  lowerLayerEncWidth = 0.03
  lowerLayerEncHeight = 0.0
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V4_0_XX_F0" {
  contactCodeNumber = 76
  cutLayer = "V4"
  lowerLayer = "M4"
  upperLayer = "M5"
  upperLayerEncWidth = 0.015
  upperLayerEncHeight = 0.015
  lowerLayerEncWidth = 0.015
  lowerLayerEncHeight = 0.015
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V4_1_XV_F0" {
  contactCodeNumber = 77
  cutLayer = "V4"
  lowerLayer = "M4"
  upperLayer = "M5"
  upperLayerEncWidth = 0.01
  upperLayerEncHeight = 0.02
  lowerLayerEncWidth = 0.015
  lowerLayerEncHeight = 0.015
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V4_1_XH_F0" {
  contactCodeNumber = 78
  cutLayer = "V4"
  lowerLayer = "M4"
  upperLayer = "M5"
  upperLayerEncWidth = 0.02
  upperLayerEncHeight = 0.01
  lowerLayerEncWidth = 0.015
  lowerLayerEncHeight = 0.015
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V4_2_XV_F0" {
  contactCodeNumber = 79
  cutLayer = "V4"
  lowerLayer = "M4"
  upperLayer = "M5"
  upperLayerEncWidth = 0.0
  upperLayerEncHeight = 0.03
  lowerLayerEncWidth = 0.015
  lowerLayerEncHeight = 0.015
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V4_2_XH_F0" {
  contactCodeNumber = 80
  cutLayer = "V4"
  lowerLayer = "M4"
  upperLayer = "M5"
  upperLayerEncWidth = 0.03
  upperLayerEncHeight = 0.0
  lowerLayerEncWidth = 0.015
  lowerLayerEncHeight = 0.015
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V4_3_HX_F0" {
  contactCodeNumber = 81
  cutLayer = "V4"
  lowerLayer = "M4"
  upperLayer = "M5"
  upperLayerEncWidth = 0.015
  upperLayerEncHeight = 0.015
  lowerLayerEncWidth = 0.02
  lowerLayerEncHeight = 0.01
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V4_3_VX_F0" {
  contactCodeNumber = 82
  cutLayer = "V4"
  lowerLayer = "M4"
  upperLayer = "M5"
  upperLayerEncWidth = 0.015
  upperLayerEncHeight = 0.015
  lowerLayerEncWidth = 0.01
  lowerLayerEncHeight = 0.02
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V4_4_HV_F0" {
  contactCodeNumber = 83
  cutLayer = "V4"
  lowerLayer = "M4"
  upperLayer = "M5"
  upperLayerEncWidth = 0.01
  upperLayerEncHeight = 0.02
  lowerLayerEncWidth = 0.02
  lowerLayerEncHeight = 0.01
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V4_4_VV_F0" {
  contactCodeNumber = 84
  cutLayer = "V4"
  lowerLayer = "M4"
  upperLayer = "M5"
  upperLayerEncWidth = 0.01
  upperLayerEncHeight = 0.02
  lowerLayerEncWidth = 0.01
  lowerLayerEncHeight = 0.02
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V4_4_HH_F0" {
  contactCodeNumber = 85
  cutLayer = "V4"
  lowerLayer = "M4"
  upperLayer = "M5"
  upperLayerEncWidth = 0.02
  upperLayerEncHeight = 0.01
  lowerLayerEncWidth = 0.02
  lowerLayerEncHeight = 0.01
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V4_4_VH_F0" {
  contactCodeNumber = 86
  cutLayer = "V4"
  lowerLayer = "M4"
  upperLayer = "M5"
  upperLayerEncWidth = 0.02
  upperLayerEncHeight = 0.01
  lowerLayerEncWidth = 0.01
  lowerLayerEncHeight = 0.02
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V4_5_HV_F0" {
  contactCodeNumber = 87
  cutLayer = "V4"
  lowerLayer = "M4"
  upperLayer = "M5"
  upperLayerEncWidth = 0.0
  upperLayerEncHeight = 0.03
  lowerLayerEncWidth = 0.02
  lowerLayerEncHeight = 0.01
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V4_5_VV_F0" {
  contactCodeNumber = 88
  cutLayer = "V4"
  lowerLayer = "M4"
  upperLayer = "M5"
  upperLayerEncWidth = 0.0
  upperLayerEncHeight = 0.03
  lowerLayerEncWidth = 0.01
  lowerLayerEncHeight = 0.02
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V4_5_HH_F0" {
  contactCodeNumber = 89
  cutLayer = "V4"
  lowerLayer = "M4"
  upperLayer = "M5"
  upperLayerEncWidth = 0.03
  upperLayerEncHeight = 0.0
  lowerLayerEncWidth = 0.02
  lowerLayerEncHeight = 0.01
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V4_5_VH_F0" {
  contactCodeNumber = 90
  cutLayer = "V4"
  lowerLayer = "M4"
  upperLayer = "M5"
  upperLayerEncWidth = 0.03
  upperLayerEncHeight = 0.0
  lowerLayerEncWidth = 0.01
  lowerLayerEncHeight = 0.02
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V4_6_HX_F0" {
  contactCodeNumber = 91
  cutLayer = "V4"
  lowerLayer = "M4"
  upperLayer = "M5"
  upperLayerEncWidth = 0.015
  upperLayerEncHeight = 0.015
  lowerLayerEncWidth = 0.03
  lowerLayerEncHeight = 0.0
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V4_6_VX_F0" {
  contactCodeNumber = 92
  cutLayer = "V4"
  lowerLayer = "M4"
  upperLayer = "M5"
  upperLayerEncWidth = 0.015
  upperLayerEncHeight = 0.015
  lowerLayerEncWidth = 0.0
  lowerLayerEncHeight = 0.03
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V4_7_HV_F0" {
  contactCodeNumber = 93
  cutLayer = "V4"
  lowerLayer = "M4"
  upperLayer = "M5"
  upperLayerEncWidth = 0.01
  upperLayerEncHeight = 0.02
  lowerLayerEncWidth = 0.03
  lowerLayerEncHeight = 0.0
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V4_7_VV_F0" {
  contactCodeNumber = 94
  cutLayer = "V4"
  lowerLayer = "M4"
  upperLayer = "M5"
  upperLayerEncWidth = 0.01
  upperLayerEncHeight = 0.02
  lowerLayerEncWidth = 0.0
  lowerLayerEncHeight = 0.03
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V4_7_HH_F0" {
  contactCodeNumber = 95
  cutLayer = "V4"
  lowerLayer = "M4"
  upperLayer = "M5"
  upperLayerEncWidth = 0.02
  upperLayerEncHeight = 0.01
  lowerLayerEncWidth = 0.03
  lowerLayerEncHeight = 0.0
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V4_7_VH_F0" {
  contactCodeNumber = 96
  cutLayer = "V4"
  lowerLayer = "M4"
  upperLayer = "M5"
  upperLayerEncWidth = 0.02
  upperLayerEncHeight = 0.01
  lowerLayerEncWidth = 0.0
  lowerLayerEncHeight = 0.03
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V4_8_HV_F0" {
  contactCodeNumber = 97
  cutLayer = "V4"
  lowerLayer = "M4"
  upperLayer = "M5"
  upperLayerEncWidth = 0.0
  upperLayerEncHeight = 0.03
  lowerLayerEncWidth = 0.03
  lowerLayerEncHeight = 0.0
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V4_8_VV_F0" {
  contactCodeNumber = 98
  cutLayer = "V4"
  lowerLayer = "M4"
  upperLayer = "M5"
  upperLayerEncWidth = 0.0
  upperLayerEncHeight = 0.03
  lowerLayerEncWidth = 0.0
  lowerLayerEncHeight = 0.03
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V4_8_HH_F0" {
  contactCodeNumber = 99
  cutLayer = "V4"
  lowerLayer = "M4"
  upperLayer = "M5"
  upperLayerEncWidth = 0.03
  upperLayerEncHeight = 0.0
  lowerLayerEncWidth = 0.03
  lowerLayerEncHeight = 0.0
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V4_8_VH_F0" {
  contactCodeNumber = 100
  cutLayer = "V4"
  lowerLayer = "M4"
  upperLayer = "M5"
  upperLayerEncWidth = 0.03
  upperLayerEncHeight = 0.0
  lowerLayerEncWidth = 0.0
  lowerLayerEncHeight = 0.03
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V5_0_XX_F0" {
  contactCodeNumber = 101
  cutLayer = "V5"
  lowerLayer = "M5"
  upperLayer = "M6"
  upperLayerEncWidth = 0.015
  upperLayerEncHeight = 0.015
  lowerLayerEncWidth = 0.015
  lowerLayerEncHeight = 0.015
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V5_1_XH_F0" {
  contactCodeNumber = 102
  cutLayer = "V5"
  lowerLayer = "M5"
  upperLayer = "M6"
  upperLayerEncWidth = 0.02
  upperLayerEncHeight = 0.01
  lowerLayerEncWidth = 0.015
  lowerLayerEncHeight = 0.015
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V5_1_XV_F0" {
  contactCodeNumber = 103
  cutLayer = "V5"
  lowerLayer = "M5"
  upperLayer = "M6"
  upperLayerEncWidth = 0.01
  upperLayerEncHeight = 0.02
  lowerLayerEncWidth = 0.015
  lowerLayerEncHeight = 0.015
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V5_2_XH_F0" {
  contactCodeNumber = 104
  cutLayer = "V5"
  lowerLayer = "M5"
  upperLayer = "M6"
  upperLayerEncWidth = 0.03
  upperLayerEncHeight = 0.0
  lowerLayerEncWidth = 0.015
  lowerLayerEncHeight = 0.015
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V5_2_XV_F0" {
  contactCodeNumber = 105
  cutLayer = "V5"
  lowerLayer = "M5"
  upperLayer = "M6"
  upperLayerEncWidth = 0.0
  upperLayerEncHeight = 0.03
  lowerLayerEncWidth = 0.015
  lowerLayerEncHeight = 0.015
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V5_3_VX_F0" {
  contactCodeNumber = 106
  cutLayer = "V5"
  lowerLayer = "M5"
  upperLayer = "M6"
  upperLayerEncWidth = 0.015
  upperLayerEncHeight = 0.015
  lowerLayerEncWidth = 0.01
  lowerLayerEncHeight = 0.02
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V5_3_HX_F0" {
  contactCodeNumber = 107
  cutLayer = "V5"
  lowerLayer = "M5"
  upperLayer = "M6"
  upperLayerEncWidth = 0.015
  upperLayerEncHeight = 0.015
  lowerLayerEncWidth = 0.02
  lowerLayerEncHeight = 0.01
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V5_4_VH_F0" {
  contactCodeNumber = 108
  cutLayer = "V5"
  lowerLayer = "M5"
  upperLayer = "M6"
  upperLayerEncWidth = 0.02
  upperLayerEncHeight = 0.01
  lowerLayerEncWidth = 0.01
  lowerLayerEncHeight = 0.02
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V5_4_HH_F0" {
  contactCodeNumber = 109
  cutLayer = "V5"
  lowerLayer = "M5"
  upperLayer = "M6"
  upperLayerEncWidth = 0.02
  upperLayerEncHeight = 0.01
  lowerLayerEncWidth = 0.02
  lowerLayerEncHeight = 0.01
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V5_4_VV_F0" {
  contactCodeNumber = 110
  cutLayer = "V5"
  lowerLayer = "M5"
  upperLayer = "M6"
  upperLayerEncWidth = 0.01
  upperLayerEncHeight = 0.02
  lowerLayerEncWidth = 0.01
  lowerLayerEncHeight = 0.02
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V5_4_HV_F0" {
  contactCodeNumber = 111
  cutLayer = "V5"
  lowerLayer = "M5"
  upperLayer = "M6"
  upperLayerEncWidth = 0.01
  upperLayerEncHeight = 0.02
  lowerLayerEncWidth = 0.02
  lowerLayerEncHeight = 0.01
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V5_5_VH_F0" {
  contactCodeNumber = 112
  cutLayer = "V5"
  lowerLayer = "M5"
  upperLayer = "M6"
  upperLayerEncWidth = 0.03
  upperLayerEncHeight = 0.0
  lowerLayerEncWidth = 0.01
  lowerLayerEncHeight = 0.02
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V5_5_HH_F0" {
  contactCodeNumber = 113
  cutLayer = "V5"
  lowerLayer = "M5"
  upperLayer = "M6"
  upperLayerEncWidth = 0.03
  upperLayerEncHeight = 0.0
  lowerLayerEncWidth = 0.02
  lowerLayerEncHeight = 0.01
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V5_5_VV_F0" {
  contactCodeNumber = 114
  cutLayer = "V5"
  lowerLayer = "M5"
  upperLayer = "M6"
  upperLayerEncWidth = 0.0
  upperLayerEncHeight = 0.03
  lowerLayerEncWidth = 0.01
  lowerLayerEncHeight = 0.02
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V5_5_HV_F0" {
  contactCodeNumber = 115
  cutLayer = "V5"
  lowerLayer = "M5"
  upperLayer = "M6"
  upperLayerEncWidth = 0.0
  upperLayerEncHeight = 0.03
  lowerLayerEncWidth = 0.02
  lowerLayerEncHeight = 0.01
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V5_6_VX_F0" {
  contactCodeNumber = 116
  cutLayer = "V5"
  lowerLayer = "M5"
  upperLayer = "M6"
  upperLayerEncWidth = 0.015
  upperLayerEncHeight = 0.015
  lowerLayerEncWidth = 0.0
  lowerLayerEncHeight = 0.03
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V5_6_HX_F0" {
  contactCodeNumber = 117
  cutLayer = "V5"
  lowerLayer = "M5"
  upperLayer = "M6"
  upperLayerEncWidth = 0.015
  upperLayerEncHeight = 0.015
  lowerLayerEncWidth = 0.03
  lowerLayerEncHeight = 0.0
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V5_7_VH_F0" {
  contactCodeNumber = 118
  cutLayer = "V5"
  lowerLayer = "M5"
  upperLayer = "M6"
  upperLayerEncWidth = 0.02
  upperLayerEncHeight = 0.01
  lowerLayerEncWidth = 0.0
  lowerLayerEncHeight = 0.03
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V5_7_HH_F0" {
  contactCodeNumber = 119
  cutLayer = "V5"
  lowerLayer = "M5"
  upperLayer = "M6"
  upperLayerEncWidth = 0.02
  upperLayerEncHeight = 0.01
  lowerLayerEncWidth = 0.03
  lowerLayerEncHeight = 0.0
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V5_7_VV_F0" {
  contactCodeNumber = 120
  cutLayer = "V5"
  lowerLayer = "M5"
  upperLayer = "M6"
  upperLayerEncWidth = 0.01
  upperLayerEncHeight = 0.02
  lowerLayerEncWidth = 0.0
  lowerLayerEncHeight = 0.03
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V5_7_HV_F0" {
  contactCodeNumber = 121
  cutLayer = "V5"
  lowerLayer = "M5"
  upperLayer = "M6"
  upperLayerEncWidth = 0.01
  upperLayerEncHeight = 0.02
  lowerLayerEncWidth = 0.03
  lowerLayerEncHeight = 0.0
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V5_8_VH_F0" {
  contactCodeNumber = 122
  cutLayer = "V5"
  lowerLayer = "M5"
  upperLayer = "M6"
  upperLayerEncWidth = 0.03
  upperLayerEncHeight = 0.0
  lowerLayerEncWidth = 0.0
  lowerLayerEncHeight = 0.03
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V5_8_HH_F0" {
  contactCodeNumber = 123
  cutLayer = "V5"
  lowerLayer = "M5"
  upperLayer = "M6"
  upperLayerEncWidth = 0.03
  upperLayerEncHeight = 0.0
  lowerLayerEncWidth = 0.03
  lowerLayerEncHeight = 0.0
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V5_8_VV_F0" {
  contactCodeNumber = 124
  cutLayer = "V5"
  lowerLayer = "M5"
  upperLayer = "M6"
  upperLayerEncWidth = 0.0
  upperLayerEncHeight = 0.03
  lowerLayerEncWidth = 0.0
  lowerLayerEncHeight = 0.03
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V5_8_HV_F0" {
  contactCodeNumber = 125
  cutLayer = "V5"
  lowerLayer = "M5"
  upperLayer = "M6"
  upperLayerEncWidth = 0.0
  upperLayerEncHeight = 0.03
  lowerLayerEncWidth = 0.03
  lowerLayerEncHeight = 0.0
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V6_0_XX_F0" {
  contactCodeNumber = 126
  cutLayer = "V6"
  lowerLayer = "M6"
  upperLayer = "M7"
  upperLayerEncWidth = 0.015
  upperLayerEncHeight = 0.015
  lowerLayerEncWidth = 0.015
  lowerLayerEncHeight = 0.015
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V6_1_XV_F0" {
  contactCodeNumber = 127
  cutLayer = "V6"
  lowerLayer = "M6"
  upperLayer = "M7"
  upperLayerEncWidth = 0.01
  upperLayerEncHeight = 0.02
  lowerLayerEncWidth = 0.015
  lowerLayerEncHeight = 0.015
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V6_1_XH_F0" {
  contactCodeNumber = 128
  cutLayer = "V6"
  lowerLayer = "M6"
  upperLayer = "M7"
  upperLayerEncWidth = 0.02
  upperLayerEncHeight = 0.01
  lowerLayerEncWidth = 0.015
  lowerLayerEncHeight = 0.015
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V6_2_XV_F0" {
  contactCodeNumber = 129
  cutLayer = "V6"
  lowerLayer = "M6"
  upperLayer = "M7"
  upperLayerEncWidth = 0.0
  upperLayerEncHeight = 0.03
  lowerLayerEncWidth = 0.015
  lowerLayerEncHeight = 0.015
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V6_2_XH_F0" {
  contactCodeNumber = 130
  cutLayer = "V6"
  lowerLayer = "M6"
  upperLayer = "M7"
  upperLayerEncWidth = 0.03
  upperLayerEncHeight = 0.0
  lowerLayerEncWidth = 0.015
  lowerLayerEncHeight = 0.015
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V6_3_HX_F0" {
  contactCodeNumber = 131
  cutLayer = "V6"
  lowerLayer = "M6"
  upperLayer = "M7"
  upperLayerEncWidth = 0.015
  upperLayerEncHeight = 0.015
  lowerLayerEncWidth = 0.02
  lowerLayerEncHeight = 0.01
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V6_3_VX_F0" {
  contactCodeNumber = 132
  cutLayer = "V6"
  lowerLayer = "M6"
  upperLayer = "M7"
  upperLayerEncWidth = 0.015
  upperLayerEncHeight = 0.015
  lowerLayerEncWidth = 0.01
  lowerLayerEncHeight = 0.02
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V6_4_HV_F0" {
  contactCodeNumber = 133
  cutLayer = "V6"
  lowerLayer = "M6"
  upperLayer = "M7"
  upperLayerEncWidth = 0.01
  upperLayerEncHeight = 0.02
  lowerLayerEncWidth = 0.02
  lowerLayerEncHeight = 0.01
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V6_4_VV_F0" {
  contactCodeNumber = 134
  cutLayer = "V6"
  lowerLayer = "M6"
  upperLayer = "M7"
  upperLayerEncWidth = 0.01
  upperLayerEncHeight = 0.02
  lowerLayerEncWidth = 0.01
  lowerLayerEncHeight = 0.02
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V6_4_HH_F0" {
  contactCodeNumber = 135
  cutLayer = "V6"
  lowerLayer = "M6"
  upperLayer = "M7"
  upperLayerEncWidth = 0.02
  upperLayerEncHeight = 0.01
  lowerLayerEncWidth = 0.02
  lowerLayerEncHeight = 0.01
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V6_4_VH_F0" {
  contactCodeNumber = 136
  cutLayer = "V6"
  lowerLayer = "M6"
  upperLayer = "M7"
  upperLayerEncWidth = 0.02
  upperLayerEncHeight = 0.01
  lowerLayerEncWidth = 0.01
  lowerLayerEncHeight = 0.02
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V6_5_HV_F0" {
  contactCodeNumber = 137
  cutLayer = "V6"
  lowerLayer = "M6"
  upperLayer = "M7"
  upperLayerEncWidth = 0.0
  upperLayerEncHeight = 0.03
  lowerLayerEncWidth = 0.02
  lowerLayerEncHeight = 0.01
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V6_5_VV_F0" {
  contactCodeNumber = 138
  cutLayer = "V6"
  lowerLayer = "M6"
  upperLayer = "M7"
  upperLayerEncWidth = 0.0
  upperLayerEncHeight = 0.03
  lowerLayerEncWidth = 0.01
  lowerLayerEncHeight = 0.02
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V6_5_HH_F0" {
  contactCodeNumber = 139
  cutLayer = "V6"
  lowerLayer = "M6"
  upperLayer = "M7"
  upperLayerEncWidth = 0.03
  upperLayerEncHeight = 0.0
  lowerLayerEncWidth = 0.02
  lowerLayerEncHeight = 0.01
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V6_5_VH_F0" {
  contactCodeNumber = 140
  cutLayer = "V6"
  lowerLayer = "M6"
  upperLayer = "M7"
  upperLayerEncWidth = 0.03
  upperLayerEncHeight = 0.0
  lowerLayerEncWidth = 0.01
  lowerLayerEncHeight = 0.02
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V6_6_HX_F0" {
  contactCodeNumber = 141
  cutLayer = "V6"
  lowerLayer = "M6"
  upperLayer = "M7"
  upperLayerEncWidth = 0.015
  upperLayerEncHeight = 0.015
  lowerLayerEncWidth = 0.03
  lowerLayerEncHeight = 0.0
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V6_6_VX_F0" {
  contactCodeNumber = 142
  cutLayer = "V6"
  lowerLayer = "M6"
  upperLayer = "M7"
  upperLayerEncWidth = 0.015
  upperLayerEncHeight = 0.015
  lowerLayerEncWidth = 0.0
  lowerLayerEncHeight = 0.03
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V6_7_HV_F0" {
  contactCodeNumber = 143
  cutLayer = "V6"
  lowerLayer = "M6"
  upperLayer = "M7"
  upperLayerEncWidth = 0.01
  upperLayerEncHeight = 0.02
  lowerLayerEncWidth = 0.03
  lowerLayerEncHeight = 0.0
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V6_7_VV_F0" {
  contactCodeNumber = 144
  cutLayer = "V6"
  lowerLayer = "M6"
  upperLayer = "M7"
  upperLayerEncWidth = 0.01
  upperLayerEncHeight = 0.02
  lowerLayerEncWidth = 0.0
  lowerLayerEncHeight = 0.03
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V6_7_HH_F0" {
  contactCodeNumber = 145
  cutLayer = "V6"
  lowerLayer = "M6"
  upperLayer = "M7"
  upperLayerEncWidth = 0.02
  upperLayerEncHeight = 0.01
  lowerLayerEncWidth = 0.03
  lowerLayerEncHeight = 0.0
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V6_7_VH_F0" {
  contactCodeNumber = 146
  cutLayer = "V6"
  lowerLayer = "M6"
  upperLayer = "M7"
  upperLayerEncWidth = 0.02
  upperLayerEncHeight = 0.01
  lowerLayerEncWidth = 0.0
  lowerLayerEncHeight = 0.03
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V6_8_HV_F0" {
  contactCodeNumber = 147
  cutLayer = "V6"
  lowerLayer = "M6"
  upperLayer = "M7"
  upperLayerEncWidth = 0.0
  upperLayerEncHeight = 0.03
  lowerLayerEncWidth = 0.03
  lowerLayerEncHeight = 0.0
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V6_8_VV_F0" {
  contactCodeNumber = 148
  cutLayer = "V6"
  lowerLayer = "M6"
  upperLayer = "M7"
  upperLayerEncWidth = 0.0
  upperLayerEncHeight = 0.03
  lowerLayerEncWidth = 0.0
  lowerLayerEncHeight = 0.03
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 1
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V6_8_HH_F0" {
  contactCodeNumber = 149
  cutLayer = "V6"
  lowerLayer = "M6"
  upperLayer = "M7"
  upperLayerEncWidth = 0.03
  upperLayerEncHeight = 0.0
  lowerLayerEncWidth = 0.03
  lowerLayerEncHeight = 0.0
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "V6_8_VH_F0" {
  contactCodeNumber = 150
  cutLayer = "V6"
  lowerLayer = "M6"
  upperLayer = "M7"
  upperLayerEncWidth = 0.03
  upperLayerEncHeight = 0.0
  lowerLayerEncWidth = 0.0
  lowerLayerEncHeight = 0.03
  cutWidth = 0.07
  cutHeight = 0.07
  minCutSpacing = 0.07
  isDefaultContact = 0
  maxNumRows = 4
  viaFarmSpacing = 0.13
}

ContactCode "TV2_0_VH_F0" {
  contactCodeNumber = 151
  cutLayer = "TV2"
  lowerLayer = "M7"
  upperLayer = "TM2"
  upperLayerEncWidth = 0.05
  upperLayerEncHeight = 0.02
  lowerLayerEncWidth = 0.02
  lowerLayerEncHeight = 0.05
  cutWidth = 0.36
  cutHeight = 0.36
  minCutSpacing = 0.36
  isDefaultContact = 1
  maxNumRows = 3
  viaFarmSpacing = 0.56
}

ContactCode "TV2_0_HH_F0" {
  contactCodeNumber = 152
  cutLayer = "TV2"
  lowerLayer = "M7"
  upperLayer = "TM2"
  upperLayerEncWidth = 0.05
  upperLayerEncHeight = 0.02
  lowerLayerEncWidth = 0.05
  lowerLayerEncHeight = 0.02
  cutWidth = 0.36
  cutHeight = 0.36
  minCutSpacing = 0.36
  isDefaultContact = 1
  maxNumRows = 3
  viaFarmSpacing = 0.56
}

ContactCode "TV2_0_VV_F0" {
  contactCodeNumber = 153
  cutLayer = "TV2"
  lowerLayer = "M7"
  upperLayer = "TM2"
  upperLayerEncWidth = 0.02
  upperLayerEncHeight = 0.05
  lowerLayerEncWidth = 0.02
  lowerLayerEncHeight = 0.05
  cutWidth = 0.36
  cutHeight = 0.36
  minCutSpacing = 0.36
  isDefaultContact = 0
  maxNumRows = 3
  viaFarmSpacing = 0.56
}

ContactCode "TV2_0_HV_F0" {
  contactCodeNumber = 154
  cutLayer = "TV2"
  lowerLayer = "M7"
  upperLayer = "TM2"
  upperLayerEncWidth = 0.02
  upperLayerEncHeight = 0.05
  lowerLayerEncWidth = 0.05
  lowerLayerEncHeight = 0.02
  cutWidth = 0.36
  cutHeight = 0.36
  minCutSpacing = 0.36
  isDefaultContact = 0
  maxNumRows = 3
  viaFarmSpacing = 0.56
}

ContactCode "PA_0_XX" {
  contactCodeNumber = 155
  cutLayer = "PA"
  lowerLayer = "TM2"
  upperLayer = "ALPA"
  upperLayerEncWidth = 1.0
  upperLayerEncHeight = 1.0
  lowerLayerEncWidth = 0.5
  lowerLayerEncHeight = 0.5
  cutWidth = 3.0
  cutHeight = 3.0
  minCutSpacing = 2
  isDefaultContact = 1
}

DesignRule {
  layer1 = "polyContBlockage"
  layer2 = "CT"
  minSpacing = 0.08
}

DesignRule {
  layer1 = "via1Blockage"
  layer2 = "V1"
  minSpacing = 0.09
}

DesignRule {
  layer1 = "via2Blockage"
  layer2 = "V2"
  minSpacing = 0.09
}

DesignRule {
  layer1 = "via3Blockage"
  layer2 = "V3"
  minSpacing = 0.09
}

DesignRule {
  layer1 = "via4Blockage"
  layer2 = "V4"
  minSpacing = 0.09
}

DesignRule {
  layer1 = "via5Blockage"
  layer2 = "V5"
  minSpacing = 0.09
}

DesignRule {
  layer1 = "via6Blockage"
  layer2 = "V6"
  minSpacing = 0.09
}

DesignRule {
  layer1 = "via7Blockage"
  layer2 = "TV2"
  minSpacing = 0.36
}

DesignRule {
  layer1 = "via8Blockage"
  layer2 = "PA"
  minSpacing = 2
}

DesignRule {
  layer1 = "M1"
  layer2 = "CT"
  fatWireViaKeepoutTblSize = 1
  fatWireViaKeepoutWidthThreshold = (  0.11  )
  fatWireViaKeepoutMinSize = (  2.0  )
  fatWireViaKeepoutEnclosure = (  0.015  )
}

PRRule {
  rowSpacingTopTop = 0.0
  rowSpacingBotBot = 0.0
  abuttableTopTop = 1
  abuttableTopBot = 0
  abuttableBotBot = 1
}

Tile "unit" {
  width = 0.19
  height = 1.26
}
